### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [alexwuml/TDDHomeWork#1]
作業完成，但 API 這樣設計會失去彈性。如果以後要針對新增的欄位做加總，就得要再開一個新的API。

若以後不需要針對 Cost 做加總了，也不可能把已經開放的方法移除。

如果未來還要支援不同的型別，那麼這樣的 API 設計就更難滿足這樣的需求。（需求中已經有提及未來有這樣的需求）

**Comment by alexwuml** [comment]
我將呼叫的API改成一個並傳入要計算的field，還請91指教..

**Comment by hatelove** [comment]
比原本的好多了，透過 string+reflection 是很標準的作法，但是要留意字串大小寫的問題。

我也提供我的 sample solution 供您參考一下，http://bit.ly/91-tdd-day1-homework-solution
第一版只有支援 Product, 第二版則透過 extension method + generic + lambda 來支援任意型別，這樣 API 語意清楚，呼叫端使用方便。也建議您可以參考一下 production code 的作法。
